FROM rockylinux:9
RUN dnf -y install procps-ng net-tools nfs-utils iproute iputils mtr strace openssh-clients rsync iscsi-initiator-utils bind-utils
RUN ssh-keygen -q -f /root/.ssh/id_rsa -O no-touch-requited



